### ISSUE TITLE
Error in solutioncode

### ISSUE THREAD

**Issue by CodingGenious** [udacity/aipnd_issues_tracker#67]
Neutral Networks -> Implement Gradient Descent -> Gradient Descent: The Code

I get this errorcode both on my code and the solutioncode:

Traceback (most recent call last): File "vm_main3.py", line 47, in <module> import main File "/tmp/vmuser_vnkabsvwes/main.py", line 2, in <module> import studentMain File "/tmp/vmuser_vnkabsvwes/studentMain.py", line 2, in <module> from gradient import nn_output, error, del_w File "/tmp/vmuser_vnkabsvwes/gradient.py", line 16 x = np.array([1, 2. 3, 4]) ^ SyntaxError: invalid syntax

**Comment by ronny-udacity** [comment]
Can't replicate the error. The starter code and solution seem to be working fine.

Please provide more context if you still have an issue.
